
package view;

public class dialogMenu extends javax.swing.JDialog {

    /**
     * Creates new form dialogMenu
     */
    public dialogMenu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastrar = new javax.swing.JMenu();
        menuItemCidade = new javax.swing.JMenuItem();
        menuItemCliente = new javax.swing.JMenuItem();
        menuItemMarca = new javax.swing.JMenuItem();
        menuItemModelo = new javax.swing.JMenuItem();
        menuItemVeiculo = new javax.swing.JMenuItem();
        menuItemFornecedor = new javax.swing.JMenuItem();
        menuItemServico = new javax.swing.JMenuItem();
        menuItemFuncao = new javax.swing.JMenuItem();
        menuItemFuncionario = new javax.swing.JMenuItem();
        menuItemProduto = new javax.swing.JMenuItem();
        menuItemFormaPagamento = new javax.swing.JMenuItem();
        menuItemOrdemServico = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu");

        menuCadastrar.setText("Cadastrar");

        menuItemCidade.setText("Cidade");
        menuItemCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCidadeActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemCidade);

        menuItemCliente.setText("Cliente");
        menuItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemClienteActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemCliente);

        menuItemMarca.setText("Marca");
        menuItemMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMarcaActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemMarca);

        menuItemModelo.setText("Modelo");
        menuItemModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemModeloActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemModelo);

        menuItemVeiculo.setText("Veículo");
        menuItemVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemVeiculoActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemVeiculo);

        menuItemFornecedor.setText("Fornecedor");
        menuItemFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFornecedorActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemFornecedor);

        menuItemServico.setText("Serviço");
        menuItemServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemServicoActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemServico);

        menuItemFuncao.setText("Função");
        menuItemFuncao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFuncaoActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemFuncao);

        menuItemFuncionario.setText("Funcionário");
        menuItemFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFuncionarioActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemFuncionario);

        menuItemProduto.setText("Produto");
        menuItemProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemProdutoActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemProduto);

        menuItemFormaPagamento.setText("Forma de Pagamento");
        menuItemFormaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemFormaPagamentoActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemFormaPagamento);

        menuItemOrdemServico.setText("Ordem de Serviço");
        menuItemOrdemServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemOrdemServicoActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemOrdemServico);

        jMenuBar1.add(menuCadastrar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCidadeActionPerformed
        new dialogCidade(null, true).setVisible(true);
    }//GEN-LAST:event_menuItemCidadeActionPerformed

    private void menuItemMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMarcaActionPerformed
        new dialogMarca(null, true).setVisible(true);
    }//GEN-LAST:event_menuItemMarcaActionPerformed

    private void menuItemModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemModeloActionPerformed
        new dialogModelo(null, true).setVisible(true);
    }//GEN-LAST:event_menuItemModeloActionPerformed

    private void menuItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemClienteActionPerformed
        new dialogCliente(null, true).setVisible(true);
    }//GEN-LAST:event_menuItemClienteActionPerformed

    private void menuItemVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemVeiculoActionPerformed
        new dialogVeiculo(null, true).setVisible(true);
    }//GEN-LAST:event_menuItemVeiculoActionPerformed

    private void menuItemFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFornecedorActionPerformed
        new dialogFornecedor(null, true).setVisible(true);
    }//GEN-LAST:event_menuItemFornecedorActionPerformed

    private void menuItemServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemServicoActionPerformed
        new dialogServico(null, true).setVisible(true);
    }//GEN-LAST:event_menuItemServicoActionPerformed

    private void menuItemFuncaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFuncaoActionPerformed
        new dialogFuncao(null, true).setVisible(true);
    }//GEN-LAST:event_menuItemFuncaoActionPerformed

    private void menuItemFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFuncionarioActionPerformed
        new dialogFuncionario(null, true).setVisible(true);
    }//GEN-LAST:event_menuItemFuncionarioActionPerformed

    private void menuItemProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemProdutoActionPerformed
        new dialogProduto(null, true).setVisible(true);
    }//GEN-LAST:event_menuItemProdutoActionPerformed

    private void menuItemFormaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemFormaPagamentoActionPerformed
        new dialogFormaPagamento(null, true).setVisible(true);
    }//GEN-LAST:event_menuItemFormaPagamentoActionPerformed

    private void menuItemOrdemServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemOrdemServicoActionPerformed
        new dialogOrdemServico(null, true).setVisible(true);
    }//GEN-LAST:event_menuItemOrdemServicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dialogMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dialogMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dialogMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dialogMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dialogMenu dialog = new dialogMenu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuCadastrar;
    private javax.swing.JMenuItem menuItemCidade;
    private javax.swing.JMenuItem menuItemCliente;
    private javax.swing.JMenuItem menuItemFormaPagamento;
    private javax.swing.JMenuItem menuItemFornecedor;
    private javax.swing.JMenuItem menuItemFuncao;
    private javax.swing.JMenuItem menuItemFuncionario;
    private javax.swing.JMenuItem menuItemMarca;
    private javax.swing.JMenuItem menuItemModelo;
    private javax.swing.JMenuItem menuItemOrdemServico;
    private javax.swing.JMenuItem menuItemProduto;
    private javax.swing.JMenuItem menuItemServico;
    private javax.swing.JMenuItem menuItemVeiculo;
    // End of variables declaration//GEN-END:variables
}
